if(CMAKE_SYSTEM_PROCESSOR STREQUAL "atmega88")
include_directories(lib/FreeRTOS/portable/GCC/AVR)
set(INSTALL_HEADERS ${INSTALL_HEADERS} lib/FreeRTOS/portable/GCC/AVR/portmacro.h)
set(OPTIONAL_SOURCE_FILES ${OPTIONAL_SOURCE_FILES} lib/FreeRTOS/portable/GCC/AVR/port.c)
set (PORT_AVR_TIMER "0" CACHE STRING "which hw timer to use")
endif(CMAKE_SYSTEM_PROCESSOR STREQUAL "atmega88")
